[package]
name = "resilience_patterns"
version = "0.1.0"
edition = "2021"
authors = ["IOT Framework Team"]
description = "基于形式化方法实现的微服务弹性模式库"
license = "MIT"
readme = "README.md"
repository = "https://github.com/iot-framework/resilience-patterns"
keywords = ["resilience", "microservices", "circuit-breaker", "retry", "service-discovery"]
categories = ["asynchronous", "concurrency", "web-programming"]

[dependencies]
tokio = { version = "1.28", features = ["full"] }
thiserror = "1.0"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
reqwest = { version = "0.11", features = ["json"] }

[dev-dependencies]
tokio-test = "0.4"

[lib]
name = "resilience_patterns"
path = "code/lib.rs"

[[example]]
name = "resilience_example"
path = "code/examples/resilience_example.rs"

[[example]]
name = "discovery_example"
path = "code/examples/discovery_example.rs" 