package stopline_test

import (
	"fmt"
	"testing"

	cm "navigate/common/model"
	api_stpl "navigate/iot/navlock/gezhouba/api/stopline"
)

func TestResponseJsonStruct(t *testing.T) {
	var stoplinestruct api_stpl.ResponseJsonStruct
	err := cm.Json.UnmarshalFromString(respBody, &stoplinestruct)
	if err != nil {
		t.Errorf("err: %+v", err)
		return
	}

	//fmt.Printf("stoplinestruct: %+v", stoplinestruct)
	var slst api_stpl.StoplineStruct
	slst.TransformFrom(&stoplinestruct)
	fmt.Printf("StoplineSt: %+v", slst)
}

var (
	respBody string = `{
    "Heart": {
        "searchValue": null,
        "createBy": "",
        "createTime": null,
        "updateBy": "",
        "updateTime": null,
        "remark": "雷达计算机心跳",
        "params": {},
        "id": 544,
        "code": "Heart",
        "zs": null,
        "modbusAddress": "04",
        "plcCode": null,
        "dataType": "Int",
        "plcAddress": null,
        "command": null,
        "result": 70,
        "type": "参数设置",
        "index": "",
        "delFlag": "0"
    },
    "XX": {
        "searchValue": null,
        "createBy": "",
        "createTime": null,
        "updateBy": "",
        "updateTime": null,
        "remark": "下行",
        "params": {},
        "id": 554,
        "code": "XX",
        "zs": null,
        "modbusAddress": "12",
        "plcCode": null,
        "dataType": "Bool",
        "plcAddress": null,
        "command": null,
        "result": 0,
        "type": "集控PLC",
        "index": "11",
        "delFlag": "0"
    },
    "F4_Open_CTRL": {
        "searchValue": null,
        "createBy": "",
        "createTime": null,
        "updateBy": "",
        "updateTime": null,
        "remark": "下右阀门开运行",
        "params": {},
        "id": 590,
        "code": "F4_Open_CTRL",
        "zs": null,
        "modbusAddress": "16",
        "plcCode": null,
        "dataType": "Bool",
        "plcAddress": null,
        "command": null,
        "result": 0,
        "type": "集控PLC",
        "index": "6",
        "delFlag": "0"
    },
    "Decter_Dis_ZB": {
        "searchValue": null,
        "createBy": "",
        "createTime": null,
        "updateBy": "",
        "updateTime": null,
        "remark": "有效目标距闸壁最小距离(cm)",
        "params": {},
        "id": 624,
        "code": "Decter_Dis_ZB",
        "zs": null,
        "modbusAddress": "67",
        "plcCode": null,
        "dataType": "Int",
        "plcAddress": null,
        "command": null,
        "result": 50,
        "type": "LD",
        "index": "",
        "delFlag": "0"
    },
    "F4_Close_CTRL": {
        "searchValue": null,
        "createBy": "",
        "createTime": null,
        "updateBy": "",
        "updateTime": null,
        "remark": "下右阀门关运行",
        "params": {},
        "id": 592,
        "code": "F4_Close_CTRL",
        "zs": null,
        "modbusAddress": "16",
        "plcCode": null,
        "dataType": "Bool",
        "plcAddress": null,
        "command": null,
        "result": 0,
        "type": "集控PLC",
        "index": "8",
        "delFlag": "0"
    },
    "R3_Opened": {
        "searchValue": null,
        "createBy": "",
        "createTime": null,
        "updateBy": "",
        "updateTime": null,
        "remark": "下左闸门开终",
        "params": {},
        "id": 577,
        "code": "R3_Opened",
        "zs": null,
        "modbusAddress": "16",
        "plcCode": null,
        "dataType": "Bool",
        "plcAddress": null,
        "command": null,
        "result": 0,
        "type": "集控PLC",
        "index": "9",
        "delFlag": "0"
    },
    "R4_Opened": {
        "searchValue": null,
        "createBy": "",
        "createTime": null,
        "updateBy": "",
        "updateTime": null,
        "remark": "下右闸门开终",
        "params": {},
        "id": 578,
        "code": "R4_Opened",
        "zs": null,
        "modbusAddress": "16",
        "plcCode": null,
        "dataType": "Bool",
        "plcAddress": null,
        "command": null,
        "result": 0,
        "type": "集控PLC",
        "index": "10",
        "delFlag": "0"
    },
    "SZS_SW": {
        "searchValue": null,
        "createBy": "",
        "createTime": null,
        "updateBy": "",
        "updateTime": null,
        "remark": "闸室水位(cm)",
        "params": {},
        "id": 595,
        "code": "SZS_SW",
        "zs": null,
        "modbusAddress": "19",
        "plcCode": null,
        "dataType": "Int",
        "plcAddress": null,
        "command": null,
        "result": 6387,
        "type": "集控PLC",
        "index": "",
        "delFlag": "0"
    },
    "R4_KD": {
        "searchValue": null,
        "createBy": "",
        "createTime": null,
        "updateBy": "",
        "updateTime": null,
        "remark": "下游右闸门开度（0-10000）",
        "params": {},
        "id": 601,
        "code": "R4_KD",
        "zs": null,
        "modbusAddress": "25",
        "plcCode": null,
        "dataType": "Int",
        "plcAddress": null,
        "command": null,
        "result": -220,
        "type": "集控PLC",
        "index": "",
        "delFlag": "0"
    },
    "F1_Close_CTRL": {
        "searchValue": null,
        "createBy": "",
        "createTime": null,
        "updateBy": "",
        "updateTime": null,
        "remark": "上左阀门关运行",
        "params": {},
        "id": 575,
        "code": "F1_Close_CTRL",
        "zs": null,
        "modbusAddress": "15",
        "plcCode": null,
        "dataType": "Bool",
        "plcAddress": null,
        "command": null,
        "result": 0,
        "type": "集控PLC",
        "index": "7",
        "delFlag": "0"
    },
    "Cross_Dis": {
        "searchValue": null,
        "createBy": "",
        "createTime": null,
        "updateBy": "",
        "updateTime": null,
        "remark": "越线距离（单位cm,正负值)",
        "params": {},
        "id": 542,
        "code": "Cross_Dis",
        "zs": null,
        "modbusAddress": "02",
        "plcCode": null,
        "dataType": "Int",
        "plcAddress": null,
        "command": null,
        "result": 0,
        "type": "参数设置",
        "index": "",
        "delFlag": "0"
    },
    "R2_Close_CTRL": {
        "searchValue": null,
        "createBy": "",
        "createTime": null,
        "updateBy": "",
        "updateTime": null,
        "remark": "上右闸门关运行",
        "params": {},
        "id": 572,
        "code": "R2_Close_CTRL",
        "zs": null,
        "modbusAddress": "15",
        "plcCode": null,
        "dataType": "Bool",
        "plcAddress": null,
        "command": null,
        "result": 0,
        "type": "集控PLC",
        "index": "4",
        "delFlag": "0"
    },
    "JTX_Width": {
        "searchValue": null,
        "createBy": "",
        "createTime": null,
        "updateBy": "",
        "updateTime": null,
        "remark": "禁停线区域宽度(cm)",
        "params": {},
        "id": 619,
        "code": "JTX_Width",
        "zs": null,
        "modbusAddress": "62",
        "plcCode": null,
        "dataType": "Int",
        "plcAddress": null,
        "command": null,
        "result": 100,
        "type": "LD",
        "index": "",
        "delFlag": "0"
    },
    "Aim_Detected": {
        "searchValue": null,
        "createBy": "",
        "createTime": null,
        "updateBy": "",
        "updateTime": null,
        "remark": "禁停线区域检测到目标",
        "params": {},
        "id": 536,
        "code": "Aim_Detected",
        "zs": null,
        "modbusAddress": "01",
        "plcCode": null,
        "dataType": "Bool",
        "plcAddress": null,
        "command": null,
        "result": 0,
        "type": "参数设置",
        "index": "12",
        "delFlag": "0"
    },
    "JTX_Zone1_Width": {
        "searchValue": null,
        "createBy": "",
        "createTime": null,
        "updateBy": "",
        "updateTime": null,
        "remark": "禁停线区域1检测宽度(cm)",
        "params": {},
        "id": 620,
        "code": "JTX_Zone1_Width",
        "zs": null,
        "modbusAddress": "63",
        "plcCode": null,
        "dataType": "Int",
        "plcAddress": null,
        "command": null,
        "result": 200,
        "type": "LD",
        "index": "",
        "delFlag": "0"
    },
    "XX_CZ": {
        "searchValue": null,
        "createBy": "",
        "createTime": null,
        "updateBy": "",
        "updateTime": null,
        "remark": "下行出闸",
        "params": {},
        "id": 558,
        "code": "XX_CZ",
        "zs": null,
        "modbusAddress": "12",
        "plcCode": null,
        "dataType": "Bool",
        "plcAddress": null,
        "command": null,
        "result": 0,
        "type": "集控PLC",
        "index": "15",
        "delFlag": "0"
    },
    "XZS_SW": {
        "searchValue": null,
        "createBy": "",
        "createTime": null,
        "updateBy": "",
        "updateTime": null,
        "remark": "下闸室水位(cm)",
        "params": {},
        "id": 596,
        "code": "XZS_SW",
        "zs": null,
        "modbusAddress": "20",
        "plcCode": null,
        "dataType": "Int",
        "plcAddress": null,
        "command": null,
        "result": 6404,
        "type": "集控PLC",
        "index": "",
        "delFlag": "0"
    },
    "R2_Open_CTRL": {
        "searchValue": null,
        "createBy": "",
        "createTime": null,
        "updateBy": "",
        "updateTime": null,
        "remark": "上右闸门开运行",
        "params": {},
        "id": 570,
        "code": "R2_Open_CTRL",
        "zs": null,
        "modbusAddress": "15",
        "plcCode": null,
        "dataType": "Bool",
        "plcAddress": null,
        "command": null,
        "result": 1,
        "type": "集控PLC",
        "index": "2",
        "delFlag": "0"
    },
    "F1_Closed": {
        "searchValue": null,
        "createBy": "",
        "createTime": null,
        "updateBy": "",
        "updateTime": null,
        "remark": "上左阀门关终",
        "params": {},
        "id": 567,
        "code": "F1_Closed",
        "zs": null,
        "modbusAddress": "15",
        "plcCode": null,
        "dataType": "Bool",
        "plcAddress": null,
        "command": null,
        "result": 0,
        "type": "集控PLC",
        "index": "15",
        "delFlag": "0"
    },
    "JTX_XY": {
        "searchValue": null,
        "createBy": "",
        "createTime": null,
        "updateBy": "",
        "updateTime": null,
        "remark": "禁停线（上游0，下游1）",
        "params": {},
        "id": 602,
        "code": "JTX_XY",
        "zs": null,
        "modbusAddress": "51",
        "plcCode": null,
        "dataType": "Bool",
        "plcAddress": null,
        "command": null,
        "result": 0,
        "type": "LD",
        "index": "9",
        "delFlag": "0"
    },
    "LD_PowerON": {
        "searchValue": null,
        "createBy": "",
        "createTime": null,
        "updateBy": "",
        "updateTime": null,
        "remark": "雷达已上电",
        "params": {},
        "id": 549,
        "code": "LD_PowerON",
        "zs": null,
        "modbusAddress": "11",
        "plcCode": null,
        "dataType": "Bool",
        "plcAddress": null,
        "command": null,
        "result": 1,
        "type": "系统运行信息",
        "index": "13",
        "delFlag": "0"
    },
    "JTX_Zone_P1": {
        "searchValue": null,
        "createBy": "",
        "createTime": null,
        "updateBy": "",
        "updateTime": null,
        "remark": "目标在禁停线+1区域",
        "params": {},
        "id": 540,
        "code": "JTX_Zone_P1",
        "zs": null,
        "modbusAddress": "01",
        "plcCode": null,
        "dataType": "Bool",
        "plcAddress": null,
        "command": null,
        "result": 0,
        "type": "参数设置",
        "index": "16",
        "delFlag": "0"
    },
    "BJQ_night_mode": {
        "searchValue": null,
        "createBy": "",
        "createTime": null,
        "updateBy": "",
        "updateTime": null,
        "remark": "报警灯夜间常亮（非常亮0，常亮1）",
        "params": {},
        "id": 604,
        "code": "BJQ_night_mode",
        "zs": null,
        "modbusAddress": "51",
        "plcCode": null,
        "dataType": "Bool",
        "plcAddress": null,
        "command": null,
        "result": 0,
        "type": "参数设置",
        "index": "11",
        "delFlag": "0"
    },
    "R1_Close_CTRL": {
        "searchValue": null,
        "createBy": "",
        "createTime": null,
        "updateBy": "",
        "updateTime": null,
        "remark": "上左闸门关运行",
        "params": {},
        "id": 571,
        "code": "R1_Close_CTRL",
        "zs": null,
        "modbusAddress": "15",
        "plcCode": null,
        "dataType": "Bool",
        "plcAddress": null,
        "command": null,
        "result": 0,
        "type": "集控PLC",
        "index": "3",
        "delFlag": "0"
    },
    "F3_Closed": {
        "searchValue": null,
        "createBy": "",
        "createTime": null,
        "updateBy": "",
        "updateTime": null,
        "remark": "下左阀门关终",
        "params": {},
        "id": 583,
        "code": "F3_Closed",
        "zs": null,
        "modbusAddress": "16",
        "plcCode": null,
        "dataType": "Bool",
        "plcAddress": null,
        "command": null,
        "result": 1,
        "type": "集控PLC",
        "index": "15",
        "delFlag": "0"
    },
    "JTX_Zone_P2": {
        "searchValue": null,
        "createBy": "",
        "createTime": null,
        "updateBy": "",
        "updateTime": null,
        "remark": "目标在禁停线+2区域",
        "params": {},
        "id": 541,
        "code": "JTX_Zone_P2",
        "zs": null,
        "modbusAddress": "01",
        "plcCode": null,
        "dataType": "Bool",
        "plcAddress": null,
        "command": null,
        "result": 0,
        "type": "参数设置",
        "index": "1",
        "delFlag": "0"
    },
    "STOP_NAV": {
        "searchValue": null,
        "createBy": "",
        "createTime": null,
        "updateBy": "",
        "updateTime": null,
        "remark": "停航",
        "params": {},
        "id": 552,
        "code": "STOP_NAV",
        "zs": null,
        "modbusAddress": "12",
        "plcCode": null,
        "dataType": "Bool",
        "plcAddress": null,
        "command": null,
        "result": 0,
        "type": "集控PLC",
        "index": "9",
        "delFlag": "0"
    },
    "JTX_Zone2_Width": {
        "searchValue": null,
        "createBy": "",
        "createTime": null,
        "updateBy": "",
        "updateTime": null,
        "remark": "禁停线区域2前后检测宽度(cm)",
        "params": {},
        "id": 621,
        "code": "JTX_Zone2_Width",
        "zs": null,
        "modbusAddress": "64",
        "plcCode": null,
        "dataType": "Int",
        "plcAddress": null,
        "command": null,
        "result": 1000,
        "type": "LD",
        "index": "",
        "delFlag": "0"
    },
    "SX_CZ": {
        "searchValue": null,
        "createBy": "",
        "createTime": null,
        "updateBy": "",
        "updateTime": null,
        "remark": "上行出闸",
        "params": {},
        "id": 556,
        "code": "SX_CZ",
        "zs": null,
        "modbusAddress": "12",
        "plcCode": null,
        "dataType": "Bool",
        "plcAddress": null,
        "command": null,
        "result": 0,
        "type": "集控PLC",
        "index": "13",
        "delFlag": "0"
    },
    "R3_KD": {
        "searchValue": null,
        "createBy": "",
        "createTime": null,
        "updateBy": "",
        "updateTime": null,
        "remark": "下游左闸门开度（0-10000）",
        "params": {},
        "id": 600,
        "code": "R3_KD",
        "zs": null,
        "modbusAddress": "24",
        "plcCode": null,
        "dataType": "Int",
        "plcAddress": null,
        "command": null,
        "result": -26,
        "type": "集控PLC",
        "index": "",
        "delFlag": "0"
    },
    "LD_JSJ_Comm_err": {
        "searchValue": null,
        "createBy": "",
        "createTime": null,
        "updateBy": "",
        "updateTime": null,
        "remark": "雷达处理计算机通讯故障",
        "params": {},
        "id": 546,
        "code": "LD_JSJ_Comm_err",
        "zs": null,
        "modbusAddress": "11",
        "plcCode": null,
        "dataType": "Bool",
        "plcAddress": null,
        "command": null,
        "result": 0,
        "type": "系统运行信息",
        "index": "10",
        "delFlag": "0"
    },
    "F1_Open_CTRL": {
        "searchValue": null,
        "createBy": "",
        "createTime": null,
        "updateBy": "",
        "updateTime": null,
        "remark": "上左阀门开运行",
        "params": {},
        "id": 573,
        "code": "F1_Open_CTRL",
        "zs": null,
        "modbusAddress": "15",
        "plcCode": null,
        "dataType": "Bool",
        "plcAddress": null,
        "command": null,
        "result": 0,
        "type": "集控PLC",
        "index": "5",
        "delFlag": "0"
    },
    "JTX_Zone": {
        "searchValue": null,
        "createBy": "",
        "createTime": null,
        "updateBy": "",
        "updateTime": null,
        "remark": "目标在禁停线区域",
        "params": {},
        "id": 539,
        "code": "JTX_Zone",
        "zs": null,
        "modbusAddress": "01",
        "plcCode": null,
        "dataType": "Bool",
        "plcAddress": null,
        "command": null,
        "result": 0,
        "type": "参数设置",
        "index": "15",
        "delFlag": "0"
    },
    "ZP_DD_Ctrl": {
        "searchValue": null,
        "createBy": "",
        "createTime": null,
        "updateBy": "",
        "updateTime": null,
        "remark": "数控转盘点动控制",
        "params": {},
        "id": 608,
        "code": "ZP_DD_Ctrl",
        "zs": null,
        "modbusAddress": "51",
        "plcCode": null,
        "dataType": "Bool",
        "plcAddress": null,
        "command": null,
        "result": 0,
        "type": "参数设置",
        "index": "15",
        "delFlag": "0"
    },
    "ZP_Motor_Speed": {
        "searchValue": null,
        "createBy": "",
        "createTime": null,
        "updateBy": "",
        "updateTime": null,
        "remark": "步进电机转速(单位rpm)",
        "params": {},
        "id": 627,
        "code": "ZP_Motor_Speed",
        "zs": null,
        "modbusAddress": "70",
        "plcCode": null,
        "dataType": "Int",
        "plcAddress": null,
        "command": null,
        "result": 20,
        "type": "LD",
        "index": "",
        "delFlag": "0"
    },
    "R1_Opened": {
        "searchValue": null,
        "createBy": "",
        "createTime": null,
        "updateBy": "",
        "updateTime": null,
        "remark": "上左闸门开终",
        "params": {},
        "id": 561,
        "code": "R1_Opened",
        "zs": null,
        "modbusAddress": "15",
        "plcCode": null,
        "dataType": "Bool",
        "plcAddress": null,
        "command": null,
        "result": 0,
        "type": "集控PLC",
        "index": "9",
        "delFlag": "0"
    },
    "F3_Close_CTRL": {
        "searchValue": null,
        "createBy": "",
        "createTime": null,
        "updateBy": "",
        "updateTime": null,
        "remark": "下左阀门关运行",
        "params": {},
        "id": 591,
        "code": "F3_Close_CTRL",
        "zs": null,
        "modbusAddress": "16",
        "plcCode": null,
        "dataType": "Bool",
        "plcAddress": null,
        "command": null,
        "result": 0,
        "type": "集控PLC",
        "index": "7",
        "delFlag": "0"
    },
    "F2_Opened": {
        "searchValue": null,
        "createBy": "",
        "createTime": null,
        "updateBy": "",
        "updateTime": null,
        "remark": "上右阀门开终",
        "params": {},
        "id": 566,
        "code": "F2_Opened",
        "zs": null,
        "modbusAddress": "15",
        "plcCode": null,
        "dataType": "Bool",
        "plcAddress": null,
        "command": null,
        "result": 0,
        "type": "集控PLC",
        "index": "14",
        "delFlag": "0"
    },
    "F4_Opened": {
        "searchValue": null,
        "createBy": "",
        "createTime": null,
        "updateBy": "",
        "updateTime": null,
        "remark": "下右阀门开终",
        "params": {},
        "id": 582,
        "code": "F4_Opened",
        "zs": null,
        "modbusAddress": "16",
        "plcCode": null,
        "dataType": "Bool",
        "plcAddress": null,
        "command": null,
        "result": 0,
        "type": "集控PLC",
        "index": "14",
        "delFlag": "0"
    },
    "Auto_Detect": {
        "searchValue": null,
        "createBy": "",
        "createTime": null,
        "updateBy": "",
        "updateTime": null,
        "remark": "自动检测开启",
        "params": {},
        "id": 606,
        "code": "Auto_Detect",
        "zs": null,
        "modbusAddress": "51",
        "plcCode": null,
        "dataType": "Bool",
        "plcAddress": null,
        "command": null,
        "result": 1,
        "type": "参数设置",
        "index": "13",
        "delFlag": "0"
    },
    "Dectected_alarm": {
        "searchValue": null,
        "createBy": "",
        "createTime": null,
        "updateBy": "",
        "updateTime": null,
        "remark": "越线警告",
        "params": {},
        "id": 551,
        "code": "Dectected_alarm",
        "zs": null,
        "modbusAddress": "11",
        "plcCode": null,
        "dataType": "Bool",
        "plcAddress": null,
        "command": null,
        "result": 0,
        "type": "系统运行信息",
        "index": "15",
        "delFlag": "0"
    },
    "Detect_SW": {
        "searchValue": null,
        "createBy": "",
        "createTime": null,
        "updateBy": "",
        "updateTime": null,
        "remark": "雷达检测水位(单位cm)",
        "params": {},
        "id": 543,
        "code": "Detect_SW",
        "zs": null,
        "modbusAddress": "03",
        "plcCode": null,
        "dataType": "Int",
        "plcAddress": null,
        "command": null,
        "result": 0,
        "type": "参数设置",
        "index": "",
        "delFlag": "0"
    },
    "Detect_Start": {
        "searchValue": null,
        "createBy": "",
        "createTime": null,
        "updateBy": "",
        "updateTime": null,
        "remark": "雷达检测已启动",
        "params": {},
        "id": 535,
        "code": "Detect_Start",
        "zs": null,
        "modbusAddress": "01",
        "plcCode": null,
        "dataType": "Bool",
        "plcAddress": null,
        "command": null,
        "result": 1,
        "type": "参数设置",
        "index": "11",
        "delFlag": "0"
    },
    "R3_Open_CTRL": {
        "searchValue": null,
        "createBy": "",
        "createTime": null,
        "updateBy": "",
        "updateTime": null,
        "remark": "下左闸门开运行",
        "params": {},
        "id": 585,
        "code": "R3_Open_CTRL",
        "zs": null,
        "modbusAddress": "16",
        "plcCode": null,
        "dataType": "Bool",
        "plcAddress": null,
        "command": null,
        "result": 0,
        "type": "集控PLC",
        "index": "1",
        "delFlag": "0"
    },
    "RESERVE_I7": {
        "searchValue": null,
        "createBy": "",
        "createTime": null,
        "updateBy": "",
        "updateTime": null,
        "remark": "水位阈值",
        "params": {},
        "id": 636,
        "code": "RESERVE_I7",
        "zs": null,
        "modbusAddress": "71",
        "plcCode": null,
        "dataType": "Int",
        "plcAddress": null,
        "command": null,
        "result": 0,
        "type": "LD",
        "index": "",
        "delFlag": "0"
    },
    "RESERVE_I6": {
        "searchValue": null,
        "createBy": "",
        "createTime": null,
        "updateBy": "",
        "updateTime": null,
        "remark": "",
        "params": {},
        "id": 635,
        "code": "RESERVE_I6",
        "zs": null,
        "modbusAddress": "10",
        "plcCode": null,
        "dataType": "Int",
        "plcAddress": null,
        "command": null,
        "result": 13407,
        "type": "参数设置",
        "index": "",
        "delFlag": "0"
    },
    "R1_Closed": {
        "searchValue": null,
        "createBy": "",
        "createTime": null,
        "updateBy": "",
        "updateTime": null,
        "remark": "上左闸门关终",
        "params": {},
        "id": 563,
        "code": "R1_Closed",
        "zs": null,
        "modbusAddress": "15",
        "plcCode": null,
        "dataType": "Bool",
        "plcAddress": null,
        "command": null,
        "result": 0,
        "type": "集控PLC",
        "index": "11",
        "delFlag": "0"
    },
    "R2_KD": {
        "searchValue": null,
        "createBy": "",
        "createTime": null,
        "updateBy": "",
        "updateTime": null,
        "remark": "上游右闸门开度（0-10000）",
        "params": {},
        "id": 599,
        "code": "R2_KD",
        "zs": null,
        "modbusAddress": "23",
        "plcCode": null,
        "dataType": "Int",
        "plcAddress": null,
        "command": null,
        "result": 9822,
        "type": "集控PLC",
        "index": "",
        "delFlag": "0"
    },
    "RESERVE_I8": {
        "searchValue": null,
        "createBy": "",
        "createTime": null,
        "updateBy": "",
        "updateTime": null,
        "remark": "雷达安装位置阈值",
        "params": {},
        "id": 637,
        "code": "RESERVE_I8",
        "zs": null,
        "modbusAddress": "72",
        "plcCode": null,
        "dataType": "Int",
        "plcAddress": null,
        "command": null,
        "result": 50,
        "type": "LD",
        "index": "",
        "delFlag": "0"
    },
    "Err": {
        "searchValue": null,
        "createBy": "",
        "createTime": null,
        "updateBy": "",
        "updateTime": null,
        "remark": "激光雷达故障",
        "params": {},
        "id": 533,
        "code": "Err",
        "zs": null,
        "modbusAddress": "01",
        "plcCode": null,
        "dataType": "Bool",
        "plcAddress": null,
        "command": null,
        "result": 0,
        "type": "参数设置",
        "index": "9",
        "delFlag": "0"
    },
    "R3_Close_CTRL": {
        "searchValue": null,
        "createBy": "",
        "createTime": null,
        "updateBy": "",
        "updateTime": null,
        "remark": "下左闸门关运行",
        "params": {},
        "id": 587,
        "code": "R3_Close_CTRL",
        "zs": null,
        "modbusAddress": "16",
        "plcCode": null,
        "dataType": "Bool",
        "plcAddress": null,
        "command": null,
        "result": 0,
        "type": "集控PLC",
        "index": "3",
        "delFlag": "0"
    },
    "ZS_Width": {
        "searchValue": null,
        "createBy": "",
        "createTime": null,
        "updateBy": "",
        "updateTime": null,
        "remark": "船闸宽度(cm)",
        "params": {},
        "id": 610,
        "code": "ZS_Width",
        "zs": null,
        "modbusAddress": "53",
        "plcCode": null,
        "dataType": "Int",
        "plcAddress": null,
        "command": null,
        "result": 3400,
        "type": "LD",
        "index": "",
        "delFlag": "0"
    },
    "F2_Open_CTRL": {
        "searchValue": null,
        "createBy": "",
        "createTime": null,
        "updateBy": "",
        "updateTime": null,
        "remark": "上右阀门开运行",
        "params": {},
        "id": 574,
        "code": "F2_Open_CTRL",
        "zs": null,
        "modbusAddress": "15",
        "plcCode": null,
        "dataType": "Bool",
        "plcAddress": null,
        "command": null,
        "result": 0,
        "type": "集控PLC",
        "index": "6",
        "delFlag": "0"
    },
    "Manual_test_b": {
        "searchValue": null,
        "createBy": "",
        "createTime": "2022-05-29 23:34:45",
        "updateBy": "",
        "updateTime": "2022-05-31 00:56:07",
        "remark": "系统测试（按钮0-1反转）",
        "params": {},
        "id": 628,
        "code": "Manual_test_b",
        "zs": null,
        "modbusAddress": "91",
        "plcCode": null,
        "dataType": "Bool",
        "plcAddress": null,
        "command": null,
        "result": 0,
        "type": "控制输入,",
        "index": "9",
        "delFlag": "0"
    },
    "SX_JZ": {
        "searchValue": null,
        "createBy": "",
        "createTime": null,
        "updateBy": "",
        "updateTime": null,
        "remark": "上行进闸",
        "params": {},
        "id": 555,
        "code": "SX_JZ",
        "zs": null,
        "modbusAddress": "12",
        "plcCode": null,
        "dataType": "Bool",
        "plcAddress": null,
        "command": null,
        "result": 0,
        "type": "集控PLC",
        "index": "12",
        "delFlag": "0"
    },
    "PIC_Catch": {
        "searchValue": null,
        "createBy": "",
        "createTime": null,
        "updateBy": "",
        "updateTime": null,
        "remark": "报警抓拍开启",
        "params": {},
        "id": 607,
        "code": "PIC_Catch",
        "zs": null,
        "modbusAddress": "51",
        "plcCode": null,
        "dataType": "Bool",
        "plcAddress": null,
        "command": null,
        "result": 0,
        "type": "参数设置",
        "index": "14",
        "delFlag": "0"
    },
    "DetectData_offset": {
        "searchValue": null,
        "createBy": "",
        "createTime": null,
        "updateBy": "",
        "updateTime": null,
        "remark": "雷达检测水位偏差过大",
        "params": {},
        "id": 547,
        "code": "DetectData_offset",
        "zs": null,
        "modbusAddress": "11",
        "plcCode": null,
        "dataType": "Bool",
        "plcAddress": null,
        "command": null,
        "result": 0,
        "type": "系统运行信息",
        "index": "11",
        "delFlag": "0"
    },
    "Detect_High_lmt": {
        "searchValue": null,
        "createBy": "",
        "createTime": null,
        "updateBy": "",
        "updateTime": null,
        "remark": "有效目标最大高度(cm)",
        "params": {},
        "id": 622,
        "code": "Detect_High_lmt",
        "zs": null,
        "modbusAddress": "65",
        "plcCode": null,
        "dataType": "Int",
        "plcAddress": null,
        "command": null,
        "result": 0,
        "type": "LD",
        "index": "",
        "delFlag": "0"
    },
    "R3_Closed": {
        "searchValue": null,
        "createBy": "",
        "createTime": null,
        "updateBy": "",
        "updateTime": null,
        "remark": "下左闸门关终",
        "params": {},
        "id": 579,
        "code": "R3_Closed",
        "zs": null,
        "modbusAddress": "16",
        "plcCode": null,
        "dataType": "Bool",
        "plcAddress": null,
        "command": null,
        "result": 1,
        "type": "集控PLC",
        "index": "11",
        "delFlag": "0"
    },
    "RESERVE_I1": {
        "searchValue": null,
        "createBy": "",
        "createTime": null,
        "updateBy": "",
        "updateTime": null,
        "remark": "",
        "params": {},
        "id": 630,
        "code": "RESERVE_I1",
        "zs": null,
        "modbusAddress": "5",
        "plcCode": null,
        "dataType": "Int",
        "plcAddress": null,
        "command": null,
        "result": -26,
        "type": "参数设置",
        "index": "",
        "delFlag": "0"
    },
    "R2_Closed": {
        "searchValue": null,
        "createBy": "",
        "createTime": null,
        "updateBy": "",
        "updateTime": null,
        "remark": "上右闸门关终",
        "params": {},
        "id": 564,
        "code": "R2_Closed",
        "zs": null,
        "modbusAddress": "15",
        "plcCode": null,
        "dataType": "Bool",
        "plcAddress": null,
        "command": null,
        "result": 0,
        "type": "集控PLC",
        "index": "12",
        "delFlag": "0"
    },
    "R4_Closed": {
        "searchValue": null,
        "createBy": "",
        "createTime": null,
        "updateBy": "",
        "updateTime": null,
        "remark": "下右闸门关终",
        "params": {},
        "id": 580,
        "code": "R4_Closed",
        "zs": null,
        "modbusAddress": "16",
        "plcCode": null,
        "dataType": "Bool",
        "plcAddress": null,
        "command": null,
        "result": 1,
        "type": "集控PLC",
        "index": "12",
        "delFlag": "0"
    },
    "F2_Close_CTRL": {
        "searchValue": null,
        "createBy": "",
        "createTime": null,
        "updateBy": "",
        "updateTime": null,
        "remark": "上右阀门关运行",
        "params": {},
        "id": 576,
        "code": "F2_Close_CTRL",
        "zs": null,
        "modbusAddress": "15",
        "plcCode": null,
        "dataType": "Bool",
        "plcAddress": null,
        "command": null,
        "result": 0,
        "type": "集控PLC",
        "index": "8",
        "delFlag": "0"
    },
    "RESERVE_I3": {
        "searchValue": null,
        "createBy": "",
        "createTime": null,
        "updateBy": "",
        "updateTime": null,
        "remark": "",
        "params": {},
        "id": 632,
        "code": "RESERVE_I3",
        "zs": null,
        "modbusAddress": "7",
        "plcCode": null,
        "dataType": "Int",
        "plcAddress": null,
        "command": null,
        "result": 7808,
        "type": "参数设置",
        "index": "",
        "delFlag": "0"
    },
    "RESERVE_I2": {
        "searchValue": null,
        "createBy": "",
        "createTime": null,
        "updateBy": "",
        "updateTime": null,
        "remark": "",
        "params": {},
        "id": 631,
        "code": "RESERVE_I2",
        "zs": null,
        "modbusAddress": "6",
        "plcCode": null,
        "dataType": "Int",
        "plcAddress": null,
        "command": null,
        "result": 0,
        "type": "参数设置",
        "index": "",
        "delFlag": "0"
    },
    "Calibrated": {
        "searchValue": null,
        "createBy": "",
        "createTime": null,
        "updateBy": "",
        "updateTime": null,
        "remark": "雷达已标定",
        "params": {},
        "id": 534,
        "code": "Calibrated",
        "zs": null,
        "modbusAddress": "01",
        "plcCode": null,
        "dataType": "Bool",
        "plcAddress": null,
        "command": null,
        "result": 1,
        "type": "参数设置",
        "index": "10",
        "delFlag": "0"
    },
    "RESERVE_I5": {
        "searchValue": null,
        "createBy": "",
        "createTime": null,
        "updateBy": "",
        "updateTime": null,
        "remark": "",
        "params": {},
        "id": 634,
        "code": "RESERVE_I5",
        "zs": null,
        "modbusAddress": "9",
        "plcCode": null,
        "dataType": "Int",
        "plcAddress": null,
        "command": null,
        "result": -36,
        "type": "参数设置",
        "index": "",
        "delFlag": "0"
    },
    "RESERVE_I4": {
        "searchValue": null,
        "createBy": "",
        "createTime": null,
        "updateBy": "",
        "updateTime": null,
        "remark": "",
        "params": {},
        "id": 633,
        "code": "RESERVE_I4",
        "zs": null,
        "modbusAddress": "8",
        "plcCode": null,
        "dataType": "Int",
        "plcAddress": null,
        "command": null,
        "result": 8834,
        "type": "参数设置",
        "index": "",
        "delFlag": "0"
    },
    "R4_Open_CTRL": {
        "searchValue": null,
        "createBy": "",
        "createTime": null,
        "updateBy": "",
        "updateTime": null,
        "remark": "下右闸门开运行",
        "params": {},
        "id": 586,
        "code": "R4_Open_CTRL",
        "zs": null,
        "modbusAddress": "16",
        "plcCode": null,
        "dataType": "Bool",
        "plcAddress": null,
        "command": null,
        "result": 0,
        "type": "集控PLC",
        "index": "2",
        "delFlag": "0"
    },
    "R1_KD": {
        "searchValue": null,
        "createBy": "",
        "createTime": null,
        "updateBy": "",
        "updateTime": null,
        "remark": "上游左闸门开度（0-10000）",
        "params": {},
        "id": 598,
        "code": "R1_KD",
        "zs": null,
        "modbusAddress": "22",
        "plcCode": null,
        "dataType": "Int",
        "plcAddress": null,
        "command": null,
        "result": 9779,
        "type": "集控PLC",
        "index": "",
        "delFlag": "0"
    },
    "F4_Closed": {
        "searchValue": null,
        "createBy": "",
        "createTime": null,
        "updateBy": "",
        "updateTime": null,
        "remark": "下右阀门关终",
        "params": {},
        "id": 584,
        "code": "F4_Closed",
        "zs": null,
        "modbusAddress": "16",
        "plcCode": null,
        "dataType": "Bool",
        "plcAddress": null,
        "command": null,
        "result": 1,
        "type": "集控PLC",
        "index": "16",
        "delFlag": "0"
    },
    "XY_SW": {
        "searchValue": null,
        "createBy": "",
        "createTime": null,
        "updateBy": "",
        "updateTime": null,
        "remark": "下游水位(cm)",
        "params": {},
        "id": 597,
        "code": "XY_SW",
        "zs": null,
        "modbusAddress": "21",
        "plcCode": null,
        "dataType": "Int",
        "plcAddress": null,
        "command": null,
        "result": 4384,
        "type": "集控PLC",
        "index": "",
        "delFlag": "0"
    },
    "JTX_Zone_N2": {
        "searchValue": null,
        "createBy": "",
        "createTime": null,
        "updateBy": "",
        "updateTime": null,
        "remark": "目标在禁停线-2区域",
        "params": {},
        "id": 537,
        "code": "JTX_Zone_N2",
        "zs": null,
        "modbusAddress": "01",
        "plcCode": null,
        "dataType": "Bool",
        "plcAddress": null,
        "command": null,
        "result": 0,
        "type": "参数设置",
        "index": "13",
        "delFlag": "0"
    },
    "F2_Closed": {
        "searchValue": null,
        "createBy": "",
        "createTime": null,
        "updateBy": "",
        "updateTime": null,
        "remark": "上右阀门关终",
        "params": {},
        "id": 568,
        "code": "F2_Closed",
        "zs": null,
        "modbusAddress": "15",
        "plcCode": null,
        "dataType": "Bool",
        "plcAddress": null,
        "command": null,
        "result": 0,
        "type": "集控PLC",
        "index": "16",
        "delFlag": "0"
    },
    "F3_Open_CTRL": {
        "searchValue": null,
        "createBy": "",
        "createTime": null,
        "updateBy": "",
        "updateTime": null,
        "remark": "下左阀门开运行",
        "params": {},
        "id": 589,
        "code": "F3_Open_CTRL",
        "zs": null,
        "modbusAddress": "16",
        "plcCode": null,
        "dataType": "Bool",
        "plcAddress": null,
        "command": null,
        "result": 0,
        "type": "集控PLC",
        "index": "5",
        "delFlag": "0"
    },
    "SX": {
        "searchValue": null,
        "createBy": "",
        "createTime": null,
        "updateBy": "",
        "updateTime": null,
        "remark": "上行",
        "params": {},
        "id": 553,
        "code": "SX",
        "zs": null,
        "modbusAddress": "12",
        "plcCode": null,
        "dataType": "Bool",
        "plcAddress": null,
        "command": null,
        "result": 1,
        "type": "集控PLC",
        "index": "10",
        "delFlag": "0"
    },
    "SY_SW": {
        "searchValue": null,
        "createBy": "",
        "createTime": null,
        "updateBy": "",
        "updateTime": null,
        "remark": "上游水位(cm)",
        "params": {},
        "id": 594,
        "code": "SY_SW",
        "zs": null,
        "modbusAddress": "18",
        "plcCode": null,
        "dataType": "Int",
        "plcAddress": null,
        "command": null,
        "result": 6386,
        "type": "集控PLC",
        "index": "",
        "delFlag": "0"
    },
    "JTX_Zone_N1": {
        "searchValue": null,
        "createBy": "",
        "createTime": null,
        "updateBy": "",
        "updateTime": null,
        "remark": "目标在禁停线-1区域",
        "params": {},
        "id": 538,
        "code": "JTX_Zone_N1",
        "zs": null,
        "modbusAddress": "01",
        "plcCode": null,
        "dataType": "Bool",
        "plcAddress": null,
        "command": null,
        "result": 0,
        "type": "参数设置",
        "index": "14",
        "delFlag": "0"
    },
    "Detect_Dis_water": {
        "searchValue": null,
        "createBy": "",
        "createTime": null,
        "updateBy": "",
        "updateTime": null,
        "remark": "有效目标距水面最小距离(cm)",
        "params": {},
        "id": 623,
        "code": "Detect_Dis_water",
        "zs": null,
        "modbusAddress": "66",
        "plcCode": null,
        "dataType": "Int",
        "plcAddress": null,
        "command": null,
        "result": 50,
        "type": "LD",
        "index": "",
        "delFlag": "0"
    },
    "R4_Close_CTRL": {
        "searchValue": null,
        "createBy": "",
        "createTime": null,
        "updateBy": "",
        "updateTime": null,
        "remark": "下右闸门关运行",
        "params": {},
        "id": 588,
        "code": "R4_Close_CTRL",
        "zs": null,
        "modbusAddress": "16",
        "plcCode": null,
        "dataType": "Bool",
        "plcAddress": null,
        "command": null,
        "result": 0,
        "type": "集控PLC",
        "index": "4",
        "delFlag": "0"
    },
    "JK_PLC_Heart": {
        "searchValue": null,
        "createBy": "",
        "createTime": null,
        "updateBy": "",
        "updateTime": null,
        "remark": "集控PLC心跳",
        "params": {},
        "id": 593,
        "code": "JK_PLC_Heart",
        "zs": null,
        "modbusAddress": "17",
        "plcCode": null,
        "dataType": "Int",
        "plcAddress": null,
        "command": null,
        "result": 27365,
        "type": "集控PLC",
        "index": "",
        "delFlag": "0"
    },
    "JTX_Right": {
        "searchValue": null,
        "createBy": "",
        "createTime": null,
        "updateBy": "",
        "updateTime": null,
        "remark": "安装位置（左侧0，右侧1）",
        "params": {},
        "id": 603,
        "code": "JTX_Right",
        "zs": null,
        "modbusAddress": "51",
        "plcCode": null,
        "dataType": "Bool",
        "plcAddress": null,
        "command": null,
        "result": 0,
        "type": "LD",
        "index": "10",
        "delFlag": "0"
    },
    "XX_JZ": {
        "searchValue": null,
        "createBy": "",
        "createTime": null,
        "updateBy": "",
        "updateTime": null,
        "remark": "下行进闸",
        "params": {},
        "id": 557,
        "code": "XX_JZ",
        "zs": null,
        "modbusAddress": "12",
        "plcCode": null,
        "dataType": "Bool",
        "plcAddress": null,
        "command": null,
        "result": 0,
        "type": "集控PLC",
        "index": "14",
        "delFlag": "0"
    },
    "LD_Z": {
        "searchValue": null,
        "createBy": "",
        "createTime": null,
        "updateBy": "",
        "updateTime": null,
        "remark": "雷达安装位置坐标Z(cm)",
        "params": {},
        "id": 613,
        "code": "LD_Z",
        "zs": null,
        "modbusAddress": "56",
        "plcCode": null,
        "dataType": "Int",
        "plcAddress": null,
        "command": null,
        "result": 7812,
        "type": "LD",
        "index": "",
        "delFlag": "0"
    },
    "Calibrate_Req": {
        "searchValue": null,
        "createBy": "",
        "createTime": null,
        "updateBy": "",
        "updateTime": null,
        "remark": "雷达已标请求",
        "params": {},
        "id": 548,
        "code": "Calibrate_Req",
        "zs": null,
        "modbusAddress": "11",
        "plcCode": null,
        "dataType": "Bool",
        "plcAddress": null,
        "command": null,
        "result": 0,
        "type": "系统运行信息",
        "index": "12",
        "delFlag": "0"
    },
    "F3_Opened": {
        "searchValue": null,
        "createBy": "",
        "createTime": null,
        "updateBy": "",
        "updateTime": null,
        "remark": "下左阀门开终",
        "params": {},
        "id": 581,
        "code": "F3_Opened",
        "zs": null,
        "modbusAddress": "16",
        "plcCode": null,
        "dataType": "Bool",
        "plcAddress": null,
        "command": null,
        "result": 0,
        "type": "集控PLC",
        "index": "13",
        "delFlag": "0"
    },
    "LD_Y": {
        "searchValue": null,
        "createBy": "",
        "createTime": null,
        "updateBy": "",
        "updateTime": null,
        "remark": "雷达安装位置坐标Y(cm)",
        "params": {},
        "id": 612,
        "code": "LD_Y",
        "zs": null,
        "modbusAddress": "55",
        "plcCode": null,
        "dataType": "Int",
        "plcAddress": null,
        "command": null,
        "result": 0,
        "type": "LD",
        "index": "",
        "delFlag": "0"
    },
    "LD_X": {
        "searchValue": null,
        "createBy": "",
        "createTime": null,
        "updateBy": "",
        "updateTime": null,
        "remark": "雷达安装位置坐标X(cm)",
        "params": {},
        "id": 611,
        "code": "LD_X",
        "zs": null,
        "modbusAddress": "54",
        "plcCode": null,
        "dataType": "Int",
        "plcAddress": null,
        "command": null,
        "result": -15,
        "type": "LD",
        "index": "",
        "delFlag": "0"
    },
    "JK_PLC_Comm_err": {
        "searchValue": null,
        "createBy": "",
        "createTime": null,
        "updateBy": "",
        "updateTime": null,
        "remark": "船闸运行信息检测PLC通讯故障",
        "params": {},
        "id": 545,
        "code": "JK_PLC_Comm_err",
        "zs": null,
        "modbusAddress": "11",
        "plcCode": null,
        "dataType": "Bool",
        "plcAddress": null,
        "command": null,
        "result": 0,
        "type": "系统运行信息",
        "index": "9",
        "delFlag": "0"
    },
    "R1_Open_CTRL": {
        "searchValue": null,
        "createBy": "",
        "createTime": null,
        "updateBy": "",
        "updateTime": null,
        "remark": "上左闸门开运行",
        "params": {},
        "id": 569,
        "code": "R1_Open_CTRL",
        "zs": null,
        "modbusAddress": "15",
        "plcCode": null,
        "dataType": "Bool",
        "plcAddress": null,
        "command": null,
        "result": 1,
        "type": "集控PLC",
        "index": "1",
        "delFlag": "0"
    },
    "Dectected_warm": {
        "searchValue": null,
        "createBy": "",
        "createTime": null,
        "updateBy": "",
        "updateTime": null,
        "remark": "越线报警",
        "params": {},
        "id": 550,
        "code": "Dectected_warm",
        "zs": null,
        "modbusAddress": "11",
        "plcCode": null,
        "dataType": "Bool",
        "plcAddress": null,
        "command": null,
        "result": 0,
        "type": "系统运行信息",
        "index": "14",
        "delFlag": "0"
    },
    "F1_Opened": {
        "searchValue": null,
        "createBy": "",
        "createTime": null,
        "updateBy": "",
        "updateTime": null,
        "remark": "上左阀门开终",
        "params": {},
        "id": 565,
        "code": "F1_Opened",
        "zs": null,
        "modbusAddress": "15",
        "plcCode": null,
        "dataType": "Bool",
        "plcAddress": null,
        "command": null,
        "result": 0,
        "type": "集控PLC",
        "index": "13",
        "delFlag": "0"
    },
    "BJQ_test_b": {
        "searchValue": null,
        "createBy": "",
        "createTime": "2022-05-29 23:37:32",
        "updateBy": "",
        "updateTime": "2022-05-31 00:56:14",
        "remark": "报警器测试按钮\\",
        "params": {},
        "id": 629,
        "code": "BJQ_test_b",
        "zs": null,
        "modbusAddress": "91",
        "plcCode": null,
        "dataType": "Bool",
        "plcAddress": null,
        "command": null,
        "result": 0,
        "type": "控制输入,",
        "index": "10",
        "delFlag": "0"
    },
    "R2_Opened": {
        "searchValue": null,
        "createBy": "",
        "createTime": null,
        "updateBy": "",
        "updateTime": null,
        "remark": "上右闸门开终",
        "params": {},
        "id": 562,
        "code": "R2_Opened",
        "zs": null,
        "modbusAddress": "15",
        "plcCode": null,
        "dataType": "Bool",
        "plcAddress": null,
        "command": null,
        "result": 0,
        "type": "集控PLC",
        "index": "10",
        "delFlag": "0"
    },
    "BJQ_Alarm_allow": {
        "searchValue": null,
        "createBy": "",
        "createTime": null,
        "updateBy": "",
        "updateTime": null,
        "remark": "报警允许",
        "params": {},
        "id": 605,
        "code": "BJQ_Alarm_allow",
        "zs": null,
        "modbusAddress": "51",
        "plcCode": null,
        "dataType": "Bool",
        "plcAddress": null,
        "command": null,
        "result": 0,
        "type": "参数设置",
        "index": "12",
        "delFlag": "0"
    },
    "ZM_High": {
        "searchValue": null,
        "createBy": "",
        "createTime": null,
        "updateBy": "",
        "updateTime": null,
        "remark": "闸面海拔高度(cm)",
        "params": {},
        "id": 609,
        "code": "ZM_High",
        "zs": null,
        "modbusAddress": "52",
        "plcCode": null,
        "dataType": "Int",
        "plcAddress": null,
        "command": null,
        "result": 7000,
        "type": "LD",
        "index": "",
        "delFlag": "0"
    }
}
`

// 	moniterJson = `
// {

//     "XX": {
//         "remark": "下行",
//         "modbusAddress": "12",
//         "dataType": "Bool",
//         "result": 0,
//         "type": "集控PLC",
//         "index": "11"
//     },
//     "F4_Open_CTRL": {
//         "remark": "下右阀门开运行",
//         "modbusAddress": "16",
//         "dataType": "Bool",
//         "result": 0,
//         "type": "集控PLC",
//         "index": "6"
//     },
//     "F4_Close_CTRL": {
//         "remark": "下右阀门关运行",
//         "modbusAddress": "16",
//         "dataType": "Bool",
//         "result": 0,
//         "type": "集控PLC",
//         "index": "8"
//     },
//     "R3_Opened": {
//         "remark": "下左闸门开终",
//         "modbusAddress": "16",
//         "dataType": "Bool",
//         "result": 0,
//         "type": "集控PLC",
//         "index": "9"
//     },
//     "R4_Opened": {
//         "remark": "下右闸门开终",
//         "modbusAddress": "16",
//         "dataType": "Bool",
//         "result": 0,
//         "type": "集控PLC",
//         "index": "10"
//     },
//     "SZS_SW": {
//         "remark": "闸室水位(cm)",
//         "modbusAddress": "19",
//         "dataType": "Int",
//         "result": 6387,
//         "type": "集控PLC",
//         "index": ""
//     },
//     "R4_KD": {
//         "remark": "下游右闸门开度（0-10000）",
//         "modbusAddress": "25",
//         "dataType": "Int",
//         "result": -220,
//         "type": "集控PLC",
//         "index": ""
//     },
//     "F1_Close_CTRL": {
//         "remark": "上左阀门关运行",
//         "modbusAddress": "15",
//         "dataType": "Bool",
//         "result": 0,
//         "type": "集控PLC",
//         "index": "7"
//     },
//     "R2_Close_CTRL": {
//         "remark": "上右闸门关运行",
//         "modbusAddress": "15",
//         "dataType": "Bool",
//         "result": 0,
//         "type": "集控PLC",
//         "index": "4"
//     },
//     "XX_CZ": {
//         "remark": "下行出闸",
//         "modbusAddress": "12",
//         "dataType": "Bool",
//         "result": 0,
//         "type": "集控PLC",
//         "index": "15"
//     },
//     "XZS_SW": {
//         "remark": "下闸室水位(cm)",
//         "modbusAddress": "20",
//         "dataType": "Int",
//         "result": 6404,
//         "type": "集控PLC",
//         "index": ""
//     },
//     "R2_Open_CTRL": {
//         "remark": "上右闸门开运行",
//         "modbusAddress": "15",
//         "dataType": "Bool",
//         "result": 1,
//         "type": "集控PLC",
//         "index": "2"
//     },
//     "F1_Closed": {
//         "remark": "上左阀门关终",
//         "modbusAddress": "15",
//         "dataType": "Bool",
//         "result": 0,
//         "type": "集控PLC",
//         "index": "15"
//     },
//     "R1_Close_CTRL": {
//         "remark": "上左闸门关运行",
//         "modbusAddress": "15",
//         "dataType": "Bool",
//         "result": 0,
//         "type": "集控PLC",
//         "index": "3"
//     },
//     "F3_Closed": {
//         "remark": "下左阀门关终",
//         "modbusAddress": "16",
//         "dataType": "Bool",
//         "result": 1,
//         "type": "集控PLC",
//         "index": "15"
//     },
//     "STOP_NAV": {
//         "remark": "停航",
//         "modbusAddress": "12",
//         "dataType": "Bool",
//         "result": 0,
//         "type": "集控PLC",
//         "index": "9"
//     },
//     "SX_CZ": {
//         "remark": "上行出闸",
//         "modbusAddress": "12",
//         "dataType": "Bool",
//         "result": 0,
//         "type": "集控PLC",
//         "index": "13"
//     },
//     "R3_KD": {
//         "remark": "下游左闸门开度（0-10000）",
//         "modbusAddress": "24",
//         "dataType": "Int",
//         "result": -26,
//         "type": "集控PLC",
//         "index": ""
//     },
//     "F1_Open_CTRL": {
//         "remark": "上左阀门开运行",
//         "modbusAddress": "15",
//         "dataType": "Bool",
//         "result": 0,
//         "type": "集控PLC",
//         "index": "5"
//     },
//     "R1_Opened": {
//         "remark": "上左闸门开终",
//         "modbusAddress": "15",
//         "dataType": "Bool",
//         "result": 0,
//         "type": "集控PLC",
//         "index": "9"
//     },
//     "F3_Close_CTRL": {
//         "remark": "下左阀门关运行",
//         "modbusAddress": "16",
//         "dataType": "Bool",
//         "result": 0,
//         "type": "集控PLC",
//         "index": "7"
//     },
//     "F2_Opened": {
//         "remark": "上右阀门开终",
//         "modbusAddress": "15",
//         "dataType": "Bool",
//         "result": 0,
//         "type": "集控PLC",
//         "index": "14"
//     },
//     "F4_Opened": {
//         "remark": "下右阀门开终",
//         "modbusAddress": "16",
//         "dataType": "Bool",
//         "result": 0,
//         "type": "集控PLC",
//         "index": "14"
//     },
//     "R3_Open_CTRL": {
//         "remark": "下左闸门开运行",
//         "modbusAddress": "16",
//         "dataType": "Bool",
//         "result": 0,
//         "type": "集控PLC",
//         "index": "1"
//     },
//     "R1_Closed": {
//         "remark": "上左闸门关终",
//         "modbusAddress": "15",
//         "dataType": "Bool",
//         "result": 0,
//         "type": "集控PLC",
//         "index": "11"
//     },
//     "R2_KD": {
//         "remark": "上游右闸门开度（0-10000）",
//         "modbusAddress": "23",
//         "dataType": "Int",
//         "result": 9822,
//         "type": "集控PLC",
//         "index": ""
//     },
//     "R3_Close_CTRL": {
//         "remark": "下左闸门关运行",
//         "modbusAddress": "16",
//         "dataType": "Bool",
//         "result": 0,
//         "type": "集控PLC",
//         "index": "3"
//     },
//     "ZS_Width": {
//         "remark": "船闸宽度(cm)",
//         "modbusAddress": "53",
//         "dataType": "Int",
//         "result": 3400,
//         "type": "LD",
//         "index": ""
//     },
//     "F2_Open_CTRL": {
//         "remark": "上右阀门开运行",
//         "modbusAddress": "15",
//         "dataType": "Bool",
//         "result": 0,
//         "type": "集控PLC",
//         "index": "6"
//     },
//     "SX_JZ": {
//         "remark": "上行进闸",
//         "modbusAddress": "12",
//         "dataType": "Bool",
//         "result": 0,
//         "type": "集控PLC",
//         "index": "12"
//     },
//     "R3_Closed": {
//         "remark": "下左闸门关终",
//         "modbusAddress": "16",
//         "dataType": "Bool",
//         "result": 1,
//         "type": "集控PLC",
//         "index": "11"
//     },
//     "R2_Closed": {
//         "remark": "上右闸门关终",
//         "modbusAddress": "15",
//         "dataType": "Bool",
//         "result": 0,
//         "type": "集控PLC",
//         "index": "12"
//     },
//     "R4_Closed": {
//         "remark": "下右闸门关终",
//         "modbusAddress": "16",
//         "dataType": "Bool",
//         "result": 1,
//         "type": "集控PLC",
//         "index": "12"
//     },
//     "F2_Close_CTRL": {
//         "remark": "上右阀门关运行",
//         "modbusAddress": "15",
//         "dataType": "Bool",
//         "result": 0,
//         "type": "集控PLC",
//         "index": "8"
//     },
//     "R4_Open_CTRL": {
//         "remark": "下右闸门开运行",
//         "modbusAddress": "16",
//         "dataType": "Bool",
//         "result": 0,
//         "type": "集控PLC",
//         "index": "2"
//     },
//     "R1_KD": {
//         "remark": "上游左闸门开度（0-10000）",
//         "modbusAddress": "22",
//         "dataType": "Int",
//         "result": 9779,
//         "type": "集控PLC",
//         "index": ""
//     },
//     "F4_Closed": {
//         "remark": "下右阀门关终",
//         "modbusAddress": "16",
//         "dataType": "Bool",
//         "result": 1,
//         "type": "集控PLC",
//         "index": "16"
//     },
//     "XY_SW": {
//         "remark": "下游水位(cm)",
//         "modbusAddress": "21",
//         "dataType": "Int",
//         "result": 4384,
//         "type": "集控PLC",
//         "index": ""
//     },
//     "F2_Closed": {
//         "remark": "上右阀门关终",
//         "modbusAddress": "15",
//         "dataType": "Bool",
//         "result": 0,
//         "type": "集控PLC",
//         "index": "16"
//     },
//     "F3_Open_CTRL": {
//         "remark": "下左阀门开运行",
//         "modbusAddress": "16",
//         "dataType": "Bool",
//         "result": 0,
//         "type": "集控PLC",
//         "index": "5"
//     },
//     "SX": {
//         "remark": "上行",
//         "modbusAddress": "12",
//         "dataType": "Bool",
//         "result": 1,
//         "type": "集控PLC",
//         "index": "10"
//     },
//     "SY_SW": {
//         "remark": "上游水位(cm)",
//         "modbusAddress": "18",
//         "dataType": "Int",
//         "result": 6386,
//         "type": "集控PLC",
//         "index": ""
//     },
//     "R4_Close_CTRL": {
//         "remark": "下右闸门关运行",
//         "modbusAddress": "16",
//         "dataType": "Bool",
//         "result": 0,
//         "type": "集控PLC",
//         "index": "4"
//     },
//     "XX_JZ": {
//         "remark": "下行进闸",
//         "modbusAddress": "12",
//         "dataType": "Bool",
//         "result": 0,
//         "type": "集控PLC",
//         "index": "14"
//     },
//     "F3_Opened": {
//         "remark": "下左阀门开终",
//         "modbusAddress": "16",
//         "dataType": "Bool",
//         "result": 0,
//         "type": "集控PLC",
//         "index": "13"
//     },
//     "R1_Open_CTRL": {
//         "remark": "上左闸门开运行",
//         "modbusAddress": "15",
//         "dataType": "Bool",
//         "result": 1,
//         "type": "集控PLC",
//         "index": "1"
//     },
//     "F1_Opened": {
//         "remark": "上左阀门开终",
//         "modbusAddress": "15",
//         "dataType": "Bool",
//         "result": 0,
//         "type": "集控PLC",
//         "index": "13"
//     },
//     "R2_Opened": {
//         "remark": "上右闸门开终",
//         "modbusAddress": "15",
//         "dataType": "Bool",
//         "result": 0,
//         "type": "集控PLC",
//         "index": "10"
//     },
//     "ZM_High": {
//         "remark": "闸面海拔高度(cm)",
//         "modbusAddress": "52",
//         "dataType": "Int",
//         "result": 7000,
//         "type": "LD",
//         "index": ""
//     }
// }
// `
// )

// type CommonStructure struct {
// 	Remark        string `json:"remark"`
// 	ModbusAddress string `json:"modbusAddress"`
// 	DataType      string `json:"dataType"`
// 	Result        int    `json:"result"`
// 	Type          string `json:"type"`
// 	Index         string `json:"index"`
// }

// type Xx = CommonStructure
// type F4OpenCTRL = CommonStructure
// type F4CloseCTRL = CommonStructure
// type R3Opened = CommonStructure
// type R4Opened = CommonStructure
// type SzsSw = CommonStructure
// type R4Kd = CommonStructure
// type F1CloseCTRL = CommonStructure
// type R2CloseCTRL = CommonStructure
// type XxCz = CommonStructure
// type XzsSw = CommonStructure
// type R2OpenCTRL = CommonStructure
// type F1Closed = CommonStructure
// type R1CloseCTRL = CommonStructure
// type F3Closed = CommonStructure
// type StopNav = CommonStructure
// type SxCz = CommonStructure
// type R3Kd = CommonStructure
// type F1OpenCTRL = CommonStructure
// type R1Opened = CommonStructure
// type F3CloseCTRL = CommonStructure
// type F2Opened = CommonStructure
// type F4Opened = CommonStructure
// type R3OpenCTRL = CommonStructure
// type R1Closed = CommonStructure
// type R2Kd = CommonStructure
// type R3CloseCTRL = CommonStructure
// type ZSWidth = CommonStructure
// type F2OpenCTRL = CommonStructure
// type SxJz = CommonStructure
// type R3Closed = CommonStructure
// type R2Closed = CommonStructure
// type R4Closed = CommonStructure
// type F2CloseCTRL = CommonStructure
// type R4OpenCTRL = CommonStructure
// type R1Kd = CommonStructure
// type F4Closed = CommonStructure
// type XySw = CommonStructure
// type F2Closed = CommonStructure
// type F3OpenCTRL = CommonStructure
// type Sx = CommonStructure
// type SySw = CommonStructure
// type R4CloseCTRL = CommonStructure
// type XxJz = CommonStructure
// type F3Opened = CommonStructure
// type F1Opened = CommonStructure
// type R2Opened = CommonStructure
// type ZMHigh = CommonStructure
// type R1OpenCTRL = CommonStructure

//	type AutoGenerated struct {
//		Xx          `json:"XX"`
//		F4OpenCTRL  `json:"F4_Open_CTRL"`
//		F4CloseCTRL `json:"F4_Close_CTRL"`
//		R3Opened    `json:"R3_Opened"`
//		R4Opened    `json:"R4_Opened"`
//		SzsSw       `json:"SZS_SW"`
//		R4Kd        `json:"R4_KD"`
//		F1CloseCTRL `json:"F1_Close_CTRL"`
//		R2CloseCTRL `json:"R2_Close_CTRL"`
//		XxCz        `json:"XX_CZ"`
//		XzsSw       `json:"XZS_SW"`
//		R2OpenCTRL  `json:"R2_Open_CTRL"`
//		F1Closed    `json:"F1_Closed"`
//		R1CloseCTRL `json:"R1_Close_CTRL"`
//		F3Closed    `json:"F3_Closed"`
//		StopNav     `json:"STOP_NAV"`
//		SxCz        `json:"SX_CZ"`
//		R3Kd        `json:"R3_KD"`
//		F1OpenCTRL  `json:"F1_Open_CTRL"`
//		R1Opened    `json:"R1_Opened"`
//		F3CloseCTRL `json:"F3_Close_CTRL"`
//		F2Opened    `json:"F2_Opened"`
//		F4Opened    `json:"F4_Opened"`
//		R3OpenCTRL  `json:"R3_Open_CTRL"`
//		R1Closed    `json:"R1_Closed"`
//		R2Kd        `json:"R2_KD"`
//		R3CloseCTRL `json:"R3_Close_CTRL"`
//		ZSWidth     `json:"ZS_Width"`
//		F2OpenCTRL  `json:"F2_Open_CTRL"`
//		SxJz        `json:"SX_JZ"`
//		R3Closed    `json:"R3_Closed"`
//		R2Closed    `json:"R2_Closed"`
//		R4Closed    `json:"R4_Closed"`
//		F2CloseCTRL `json:"F2_Close_CTRL"`
//		R4OpenCTRL  `json:"R4_Open_CTRL"`
//		R1Kd        `json:"R1_KD"`
//		F4Closed    `json:"F4_Closed"`
//		XySw        `json:"XY_SW"`
//		F2Closed    `json:"F2_Closed"`
//		F3OpenCTRL  `json:"F3_Open_CTRL"`
//		Sx          `json:"SX"`
//		SySw        `json:"SY_SW"`
//		R4CloseCTRL `json:"R4_Close_CTRL"`
//		XxJz        `json:"XX_JZ"`
//		F3Opened    `json:"F3_Opened"`
//		R1OpenCTRL  `json:"R1_Open_CTRL"`
//		F1Opened    `json:"F1_Opened"`
//		R2Opened    `json:"R2_Opened"`
//		ZMHigh      `json:"ZM_High"`
//	}
)
